<a href="https://colab.research.google.com/github/myra2004/newweekN_lab/blob/main/A85204924072_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)

In [1]:
import numpy as np

def show(label, value):
    # Prints your answer, or a reminder if you have not answered yet.
    if value is None:
        print(f"{label}: not answered yet")
    else:
        print(f"{label}:\n{value}\n")

In [9]:
# (a)
v = np.array([3, 6, 9, 12, 15])  # 1-D

# (b)
M = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2-D

# (c)
T = np.array([[[1, 2, 3],
              [4, 5, 6]],

             [[7, 8, 9],
              [10, 11, 12]]])  # 3-D

# (d)
Z = np.zeros([3, 3])  # 3x3 zeros
O = np.ones(5)  # 5 ones

# (e)
v_ndim = v.ndim  # v.ndim
M_ndim = M.ndim  # M.ndim
T_ndim = T.ndim  # T.ndim
T_shape = T.shape  # T.shape

print("v", v)
print("M", M)
print("T", T)
print("Z", Z)
print("O", O)
print("v_ndim", v_ndim)
print("M_ndim", M_ndim)
print("T_ndim", T_ndim)
print("T_shape", T_shape)

v [ 3  6  9 12 15]
M [[1 2 3]
 [4 5 6]]
T [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Z [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
O [1. 1. 1. 1. 1.]
v_ndim 1
M_ndim 2
T_ndim 3
T_shape (2, 2, 3)


In [22]:
rain = np.array([0, 12, 5, 30, 8, 0, 17])

scores = np.array([[72, 88, 65],
                   [85, 79, 90],
                   [60, 71, 74],
                   [93, 84, 58]])

first_day = rain[0]  # rainfall for 1st day
last_day = rain[-1]  # rainfall for last day

mid_days = rain[1:5]  # rainfall for  2nd, 3rd amf 4th days

student1 = scores[0]  # scores for studen1 (index 0)

physics = scores[:, 1]  # columns for phsics

s3_math = scores[2, 2]  # the mark of math for student 3
top_left = scores[0:2, 0:2]  # the first two rows and first two columns

print("first_day", first_day)
print("last_day", last_day)
print("mid_days", mid_days)
print("student1", student1)
print("physics", physics)
print("s3_math", s3_math)
print("top_left", top_left)

first_day 0
last_day 17
mid_days [12  5 30  8]
student1 [72 88 65]
physics [88 79 71 84]
s3_math 74
top_left [[72 88]
 [85 79]]


In [27]:
sales = np.array([[[12,  7, 30,  4],
                   [9, 15, 22,  6],
                   [20,  3, 18, 11]],

                  [[14,  5, 28,  9],
                   [11, 15, 25,  2],
                   [17,  8, 21, 13]]])  # somehow I get it, there are 2weeks, 6 stores, 24products

sales_ndim = sales.ndim  # sales.ndim
sales_shape = sales.shape  # sales.shape

week0 = sales[1]  # sales for 1st week

w1_store2 = sales[0, 1]  # take week1, store 2 [9, 15, 22, 6]

one_value = sales[0, 0, -1]  # weeek 1, store 1, last product

w1_product0 = sales[0, :, 0]  # week 1, all first products in each stores (12, 9, 20)

print("sales_ndim", sales_ndim)
print("sales_shape", sales_shape)
print("week0", week0)
print("w1_store2", w1_store2)
print("one_value", one_value)
print("w1_product0", w1_product0)

sales_ndim 3
sales_shape (2, 3, 4)
week0 [[14  5 28  9]
 [11 15 25  2]
 [17  8 21 13]]
w1_store2 [ 9 15 22  6]
one_value 4
w1_product0 [12  9 20]


In [32]:
a = np.array([4, 8, 15, 16])
b = np.array([10, 20, 30, 40])

jan = np.array([[5, 3, 8],
                [2, 7, 4]])
feb = np.array([[6, 1, 9],
                [4, 7, 2]])

T1 = np.arange(8).reshape(2, 2, 2)
T2 = np.full((2, 2, 2), 10)

bonus = np.array([1, 0, 5])

ab_sum = a + b  # a+b
ab_diff = b - a  # b-a

total = jan + feb  # YOUR CODE HERE
change = feb - jan  # YOUR CODE HERE

T_sum = T1 + T2  # YOUR CODE HERE

jan_plus10 = jan + 10  # YOUR CODE HERE

jan_bonus = jan + bonus  # YOUR CODE HERE

print("ab_sum", ab_sum)
print("ab_diff", ab_diff)
print("total", total)
print("change", change)
print("T_sum", T_sum)
print("jan_plus10", jan_plus10)
print("jan_bonus", jan_bonus)

ab_sum [14 28 45 56]
ab_diff [ 6 12 15 24]
total [[11  4 17]
 [ 6 14  6]]
change [[ 1 -2  1]
 [ 2  0 -2]]
T_sum [[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]
jan_plus10 [[15 13 18]
 [12 17 14]]
jan_bonus [[ 6  3 13]
 [ 3  7  9]]
