<a href="https://colab.research.google.com/github/myra2004/newweekN_lab/blob/main/A85204924072_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)

In [1]:
import numpy as np

def show(label, value):
    # Prints your answer, or a reminder if you have not answered yet.
    if value is None:
        print(f"{label}: not answered yet")
    else:
        print(f"{label}:\n{value}\n")

In [9]:
# (a)
v = np.array([3, 6, 9, 12, 15])  # 1-D

# (b)
M = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2-D

# (c)
T = np.array([[[1, 2, 3],
              [4, 5, 6]],

             [[7, 8, 9],
              [10, 11, 12]]])  # 3-D

# (d)
Z = np.zeros([3, 3])  # 3x3 zeros
O = np.ones(5)  # 5 ones

# (e)
v_ndim = v.ndim  # v.ndim
M_ndim = M.ndim  # M.ndim
T_ndim = T.ndim  # T.ndim
T_shape = T.shape  # T.shape

print("v", v)
print("M", M)
print("T", T)
print("Z", Z)
print("O", O)
print("v_ndim", v_ndim)
print("M_ndim", M_ndim)
print("T_ndim", T_ndim)
print("T_shape", T_shape)

v [ 3  6  9 12 15]
M [[1 2 3]
 [4 5 6]]
T [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Z [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
O [1. 1. 1. 1. 1.]
v_ndim 1
M_ndim 2
T_ndim 3
T_shape (2, 2, 3)


In [22]:
rain = np.array([0, 12, 5, 30, 8, 0, 17])

scores = np.array([[72, 88, 65],
                   [85, 79, 90],
                   [60, 71, 74],
                   [93, 84, 58]])

first_day = rain[0]  # rainfall for 1st day
last_day = rain[-1]  # rainfall for last day

mid_days = rain[1:5]  # rainfall for  2nd, 3rd amf 4th days

student1 = scores[0]  # scores for studen1 (index 0)

physics = scores[:, 1]  # columns for phsics

s3_math = scores[2, 2]  # the mark of math for student 3
top_left = scores[0:2, 0:2]  # YOUR CODE HERE

print("first_day", first_day)
print("last_day", last_day)
print("mid_days", mid_days)
print("student1", student1)
print("physics", physics)
print("s3_math", s3_math)
print("top_left", top_left)

first_day 0
last_day 17
mid_days [12  5 30  8]
student1 [72 88 65]
physics [88 79 71 84]
s3_math 74
top_left [[72 88]
 [85 79]]
