<a href="https://colab.research.google.com/github/myra2004/newweekN_lab/blob/main/A85204924072_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import time

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


In [3]:
import numpy as np

def show(label, value):
    # Prints your answer, or a reminder if you have not answered yet.
    if value is None:
        print(f"{label}: not answered yet")
    else:
        print(f"{label}:\n{value}\n")

In [4]:
# (a)
v = np.array([3, 6, 9, 12, 15])  # 1-D

# (b)
M = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2-D

# (c)
T = np.array([[[1, 2, 3],
              [4, 5, 6]],

             [[7, 8, 9],
              [10, 11, 12]]])  # 3-D

# (d)
Z = np.zeros([3, 3])  # 3x3 zeros
O = np.ones(5)  # 5 ones

# (e)
v_ndim = v.ndim  # v.ndim
M_ndim = M.ndim  # M.ndim
T_ndim = T.ndim  # T.ndim
T_shape = T.shape  # T.shape

print("v", v)
print("M", M)
print("T", T)
print("Z", Z)
print("O", O)
print("v_ndim", v_ndim)
print("M_ndim", M_ndim)
print("T_ndim", T_ndim)
print("T_shape", T_shape)

v [ 3  6  9 12 15]
M [[1 2 3]
 [4 5 6]]
T [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Z [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
O [1. 1. 1. 1. 1.]
v_ndim 1
M_ndim 2
T_ndim 3
T_shape (2, 2, 3)


In [5]:
rain = np.array([0, 12, 5, 30, 8, 0, 17])

scores = np.array([[72, 88, 65],
                   [85, 79, 90],
                   [60, 71, 74],
                   [93, 84, 58]])

first_day = rain[0]  # rainfall for 1st day
last_day = rain[-1]  # rainfall for last day

mid_days = rain[1:5]  # rainfall for  2nd, 3rd amf 4th days

student1 = scores[0]  # scores for studen1 (index 0)

physics = scores[:, 1]  # columns for phsics

s3_math = scores[2, 2]  # the mark of math for student 3
top_left = scores[0:2, 0:2]  # the first two rows and first two columns

print("first_day", first_day)
print("last_day", last_day)
print("mid_days", mid_days)
print("student1", student1)
print("physics", physics)
print("s3_math", s3_math)
print("top_left", top_left)

first_day 0
last_day 17
mid_days [12  5 30  8]
student1 [72 88 65]
physics [88 79 71 84]
s3_math 74
top_left [[72 88]
 [85 79]]


In [6]:
sales = np.array([[[12,  7, 30,  4],
                   [9, 15, 22,  6],
                   [20,  3, 18, 11]],

                  [[14,  5, 28,  9],
                   [11, 15, 25,  2],
                   [17,  8, 21, 13]]])  # somehow I get it, there are 2weeks, 6 stores, 24products

sales_ndim = sales.ndim  # sales.ndim
sales_shape = sales.shape  # sales.shape

week0 = sales[1]  # sales for 1st week

w1_store2 = sales[0, 1]  # take week1, store 2 [9, 15, 22, 6]

one_value = sales[0, 0, -1]  # weeek 1, store 1, last product

w1_product0 = sales[0, :, 0]  # week 1, all first products in each stores (12, 9, 20)

print("sales_ndim", sales_ndim)
print("sales_shape", sales_shape)
print("week0", week0)
print("w1_store2", w1_store2)
print("one_value", one_value)
print("w1_product0", w1_product0)

sales_ndim 3
sales_shape (2, 3, 4)
week0 [[14  5 28  9]
 [11 15 25  2]
 [17  8 21 13]]
w1_store2 [ 9 15 22  6]
one_value 4
w1_product0 [12  9 20]


In [7]:
a = np.array([4, 8, 15, 16])
b = np.array([10, 20, 30, 40])

jan = np.array([[5, 3, 8],
                [2, 7, 4]])
feb = np.array([[6, 1, 9],
                [4, 7, 2]])

T1 = np.arange(8).reshape(2, 2, 2)
T2 = np.full((2, 2, 2), 10)

bonus = np.array([1, 0, 5])

ab_sum = a + b  # a+b
ab_diff = b - a  # b-a

total = jan + feb  # YOUR CODE HERE
change = feb - jan  # YOUR CODE HERE

T_sum = T1 + T2  # YOUR CODE HERE

jan_plus10 = jan + 10  # YOUR CODE HERE

jan_bonus = jan + bonus  # YOUR CODE HERE

print("ab_sum", ab_sum)
print("ab_diff", ab_diff)
print("total", total)
print("change", change)
print("T_sum", T_sum)
print("jan_plus10", jan_plus10)
print("jan_bonus", jan_bonus)

ab_sum [14 28 45 56]
ab_diff [ 6 12 15 24]
total [[11  4 17]
 [ 6 14  6]]
change [[ 1 -2  1]
 [ 2  0 -2]]
T_sum [[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]
jan_plus10 [[15 13 18]
 [12 17 14]]
jan_bonus [[ 6  3 13]
 [ 3  7  9]]


In [18]:
price = np.array([2.5, 4.0, 1.0, 10.0])
qty = np.array([4, 2, 10, 1])

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 3]])

P = np.array([[1, 2, 3],
              [4, 5, 6]])
C = np.array([[1, 0],
              [2, 1],
              [0, 3]])

cost = price * qty  # price times quantity

bill = price @ qty  # price and qty in dot product

elem = A * B  # element wise when matrix is with 2 dimension
prod = A @ B  # matrix product

PC = P @ C  # matrix product of P and C
PC_shape = PC.shape  # shape of P @ C

print("cost", cost)
print("bill", bill)
print("elem", elem)
print("prod", prod)
print("PC", PC)
print("PC_shape", PC_shape)



cost [10.  8. 10. 10.]
bill 38.0
elem [[ 2  0]
 [ 3 12]]
prod [[ 4  6]
 [10 12]]
PC [[ 5 11]
 [14 23]]
PC_shape (2, 2)


In [17]:
CC = C @ C

print('CC',)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Answer for e

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

It means size of C is 3x2, but when we multiply C to itself, the size of column first C is not equal to the size of rows second C

C1(3x2) != C2(3x2)

In [37]:
err = np.array([-1.5, 3.0, -2.5, 0.5, 4.0, -0.5])

D = np.array([[ 3, -1],
              [-4,  2]])

D3 = np.array([[[-1,  2], [ 3, -4]],
               [[ 5, -6], [-7,  8]]])

y_true = np.array([10.0, 12.0, 9.0, 15.0])
y_pred = np.array([11.0, 10.0, 9.5, 14.0])

abs_err = np.abs(err)  # absolute values of err

neg_D = (-D)  # negation of D

abs_D3 = np.abs(D3)  # absolute of  D3

mae = np.mean(np.abs(y_true - y_pred))  # mean absolute error between y_true and y_pred

n_big = np.prod(abs_err.shape) > 2  # YOUR CODE HERE

print("abs_err", abs_err)
print("neg_D", neg_D)
print("abs_D3", abs_D3)
print("mae", mae)
print("n_big", n_big)

abs_err [1.5 3.  2.5 0.5 4.  0.5]
neg_D [[-3  1]
 [ 4 -2]]
abs_D3 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
mae 1.125
n_big True


the last one, np.prod(abs_err.shape) returns how many elements in this variable, but cant understand why when I took greater then 2 returns True

In [44]:
ages = np.array([21, 19, 23, 20])

# 3 houses, 2 features: area (m^2) and number of rooms
H = np.array([[ 85, 2],
              [150, 4],
              [ 60, 1]])
H2 = np.array([[ 90, 3],
               [120, 3],
               [ 70, 2]])

new_house = np.array([110, 3])
floors = np.array([2, 5, 1])

ages_add = np.append(ages, 50)  # add element

ages_del = np.delete(ages, 1)  # to delete element at index

H_row = np.vstack([H, [20, 15]])  # to add rows

H_col = np.column_stack([H, [12, 7, 6]])  # to add columns

H_no_first_col = np.delete(H, 0, axis=1)  # axis=1 is column
H3 = np.stack([H, H2])  # YOUR CODE HERE

print("ages_add", ages_add)
print("ages_del", ages_del)
print("H_row", H_row)
print("H_col", H_col)
print("H_no_first_col", H_no_first_col)
print("H3", H3)
print("H3 shape", None if H3 is None else H3.shape)

ages_add [21 19 23 20 50]
ages_del [21 23 20]
H_row [[ 85   2]
 [150   4]
 [ 60   1]
 [ 20  15]]
H_col [[ 85   2  12]
 [150   4   7]
 [ 60   1   6]]
H_no_first_col [[2]
 [4]
 [1]]
H3 [[[ 85   2]
  [150   4]
  [ 60   1]]

 [[ 90   3]
  [120   3]
  [ 70   2]]]
H3 shape (2, 3, 2)


In [5]:
temps = np.array([18, 21, 25, 23, 27, 16, 20])

scores = np.array([[72, 88, 65],
                   [85, 79, 90],
                   [60, 71, 74],
                   [93, 84, 58]])

sales = np.array([[[12,  7, 30,  4],
                   [ 9, 15, 22,  6],
                   [20,  3, 18, 11]],
                  [[14,  5, 28,  9],
                   [11, 15, 25,  2],
                   [17,  8, 21, 13]]])

t_max = temps.max()  # I m lazy to write comments))
t_min = temps.min()  # YOUR CODE HERE
t_sum = temps.sum()  # YOUR CODE HERE

hottest_day = temps.argmax()  # YOUR CODE HERE

student_total = scores.sum(axis=1)  # YOUR CODE HERE

subject_best = scores.max(axis=0)  # YOUR CODE HERE

class_mean = scores.mean(axis=0)  # YOUR CODE HERE
all_sales = sales.sum()  # YOUR CODE HERE

print("t_max", t_max)
print("t_min", t_min)
print("t_sum", t_sum)
print("hottest_day", hottest_day)
print("student_total", student_total)
print("subject_best", subject_best)
print("class_mean", class_mean)
print("all_sales", all_sales)

t_max 27
t_min 16
t_sum 150
hottest_day 4
student_total [225 254 205 235]
subject_best [93 88 90]
class_mean [77.5  80.5  71.75]
all_sales 325


In [10]:
N = np.array([[1, 2],
              [3, 4],
              [5, 6]])          # shape (3, 2)

u = np.array([7, 8, 9])         # 1-D

r = np.array([[1, 2, 3, 4]])    # 2-D, shape (1, 4)

N_T = N.T  # YOUR CODE HERE
N_T_shape = N.T.shape  # YOUR CODE HERE

u_T_shape = u.T.shape  # YOUR CODE HERE

r_T = r.T  # YOUR CODE HERE
r_T_shape = r.T.shape  # YOUR CODE HERE

back = N.T.T  # YOUR CODE HERE

G = N.T @ N  # YOUR CODE HERE
G_shape = G.shape  # YOUR CODE HERE

print("N_T", N_T)
print("N_T_shape", N_T_shape)
print("u_T_shape", u_T_shape)
print("r_T", r_T)
print("r_T_shape", r_T_shape)
print("back", back)
print("G", G)
print("G_shape", G_shape)

N_T [[1 3 5]
 [2 4 6]]
N_T_shape (2, 3)
u_T_shape (3,)
r_T [[1]
 [2]
 [3]
 [4]]
r_T_shape (4, 1)
back [[1 2]
 [3 4]
 [5 6]]
G [[35 44]
 [44 56]]
G_shape (2, 2)


answer for b

u matrix didnt change, bcs of it one dimension. row is 1, columns are 3. when row 1 goes to column 1, row 2 goes to column 2, but we dont have any rows except 1

In [16]:
celsius = np.array([0, 10, 20, 30, 40])

nums = np.array([1, 2, 3, 4, 5, 6])

# 5 days, 2 features: temperature and visitors (in hundreds)
X = np.array([[20, 3],
              [25, 5],
              [18, 2],
              [30, 6],
              [22, 4]])
y = np.array([52, 75, 40, 96, 60])   # true sales

w = np.array([1.5, 8.0])
b = 2.0

celsius_to_f = celsius * 1.8 + 32  # YOUR CODE HERE

squares = np.square(nums)  # YOUR CODE HERE
sum_squares = squares.sum()  # YOUR CODE HERE

y_hat = X @ w + b  # YOUR CODE HERE

errors = y - y_hat  # YOUR CODE HERE

mse = np.mean(errors ** 2)  # YOUR CODE HERE

show("celsius_to_f", celsius_to_f)
show("squares", squares)
show("sum_squares", sum_squares)
show("y_hat", y_hat)
show("errors", errors)
show("mse", mse)

celsius_to_f:
[ 32.  50.  68.  86. 104.]

squares:
[ 1  4  9 16 25 36]

sum_squares:
91

y_hat:
[56.  79.5 45.  95.  67. ]

errors:
[-4.  -4.5 -5.   1.  -7. ]

mse:
22.25

